from sqlalchemy import Column, String, Float, BigInteger, Text, Numeric, Boolean, Integer
from .database import Base


class Pago(Base):
    __tablename__ = "pagos"
    
    folio_venta = Column("Folio de la venta", BigInteger, primary_key=True)
    numero_pago = Column("Número de pago", String(255), primary_key=True)
    folio_pago = Column("Folio de pago", String(255), primary_key=True)
    cliente = Column("Cliente", String(255), primary_key=True)
    id_pago = Column("ID Pago", String(255))
    id_flujo = Column("ID Flujo", String(255))
    estatus_flujo = Column("Estatus flujo", Text)
    monto_flujo = Column("Monto flujo", Numeric(20, 4))
    
    
    fecha_estatus = Column("Fecha del estatus finalizado", Text)
    proyecto = Column("Proyecto", Text)
    etapa = Column("Etapa", Text)
    privada = Column("Privada", Text)
    unidad = Column("Unidad", BigInteger)
    superficie = Column("Superficie M2", Numeric(20, 4))
    plazo_enganche = Column("Plazo enganche", BigInteger)
    apartado = Column("Apartado", Numeric(20, 4))
    promocion = Column("Promoción", Text)
    fecha_amortizacion = Column("Fecha de amortización", Text)
    concepto_pago = Column("Concepto de pago", Text)
    monto_a_pagar = Column("Monto a pagar", Numeric(20, 4))
    fecha_comprobante = Column("Fecha del comprobante de pago", Text)
    metodo_pago = Column("Método de pago", Text)
    tipo_pago = Column("Tipo de pago", Text)
    banco_caja = Column("Banco Caja", Text)
    monto_pagado = Column("Monto pagado", Numeric(20, 4))
    fecha_aplicacion = Column("Fecha de aplicación de pago registro en sistema", Text)
    estatus = Column("Estatus", Text)
    estatus_expediente = Column("Estatus expediente", Text)
    fecha_cancelacion = Column("Fecha de cancelación", Text)
    cancelado_por = Column("Cancelado por", Text)
    asesor = Column("Asesor", Text)
    tipo_moneda = Column("Tipo de moneda", Text)
    observaciones = Column("Observaciones", Text)

# --- VENTAS ---
class Venta(Base):
    __tablename__ = "ventas"
    folio = Column("FOLIO", String(255), primary_key=True)
    desarrollo = Column("DESARROLLO", Text)
    etapa = Column("ETAPA", Text)
    numero = Column("NÚMERO", Text)
    clasificador = Column("CLASIFICADOR", Text)
    metros_cuadrados = Column("METROS CUADRADOS", Numeric(20, 4))
    id_cliente = Column("ID CLIENTE", Float)
    id_cliente_2 = Column("ID CLIENTE_2", Float)
    id_cliente_3 = Column("ID CLIENTE_3", Float)
    id_cliente_4 = Column("ID CLIENTE_4", Float)
    id_cliente_5 = Column("ID CLIENTE_5", Float)
    id_cliente_6 = Column("ID CLIENTE_6", Float)
    cliente = Column("CLIENTE", Text)
    cliente_2 = Column("CLIENTE_2", Text)
    cliente_3 = Column("CLIENTE_3", Text)
    cliente_4 = Column("CLIENTE_4", Text)
    cliente_5 = Column("CLIENTE_5", Text)
    cliente_6 = Column("CLIENTE_6", Text)
    telefono = Column("TELÉFONO", Text)
    asesor = Column("ASESOR", Text)
    canal_ventas = Column("CANAL DE VENTAS", Text)
    precio_lista = Column("PRECIO DE LISTA", Numeric(20, 4))
    descuento = Column("DESCUENTO", Text)
    total_enganche = Column("TOTAL GENERAL DE ENGANCHE", Numeric(20, 4))
    flujo_enganche = Column("FLUJO DE ENGANCHE", Numeric(20, 4))
    meses_enganche = Column("MESES DE ENGANCHE", Text)
    monto_sin_interes = Column("MONTO FINANCIADO SIN INTERESES", Numeric(20, 4))
    monto_con_interes = Column("MONTO FINANCIADO CON INTERESES", Numeric(20, 4))
    precio_final = Column("PRECIO FINAL", Numeric(20, 4))
    apartado = Column("APARTADO", Numeric(20, 4))
    fecha_inicio_operacion = Column("FECHA DE INICIO DE OPERACIÓN", Text)
    fecha_pago_apartado = Column("FECHA DE PAGO DE APARTADO", Text)
    fecha_finalizacion_enganche = Column("FECHA DE FINALIZACIÓN DE ENGANCHE", Text)
    fecha_venta = Column("FECHA DE VENTA", Text)
    fecha_finalizacion_financiamiento = Column("FECHA DE FINALIZACIÓN DE FINANCIAMIENTO", Text)
    responsables = Column("RESPONSABLES", Text)
    fecha_firma = Column("FECHA DE FIRMA DE PROMESA DE COMPRAVENTA", Float)
    fecha_fin_pago_enganche = Column("FECHA DE FINALIZACIÓN DE PAGO DE ENGANCHE", Text)
    plazo_financiamiento = Column("PLAZO DE FINANCIAMIENTO", Text)
    tipo_moneda = Column("TIPO DE MONEDA", Text)
    estado_expediente = Column("ESTADO DEL EXPEDIENTE", Text)
    correo_electronico = Column("CORREO ELECTRÓNICO", Text)
    genero = Column("GÉNERO", Text)
    fecha_nacimiento = Column("FECHA DE NACIMIENTO", Text)
    lugar_nacimiento = Column("LUGAR DE NACIMIENTO", Text)
    ocupacion = Column("OCUPACIÓN", Text)
    estado_civil = Column("ESTADO CIVIL", Text)
    estado = Column("ESTADO", Text)
    pais = Column("PAÍS", Text)
    coordinador = Column("COORDINADOR COMERCIAL", Float)
    gerente = Column("GERENTE COMERCIAL", Text)

# --- CARTERA VENCIDA ---
class Cartera(Base):
    __tablename__ = "cartera_vencida"
    folio = Column("FOLIO", BigInteger, primary_key=True)
    reporte = Column("REPORTE", Text)
    proyecto = Column("PROYECTO", Text)
    fase = Column("FASE", Text)
    etapa = Column("ETAPA", Text)
    unidad = Column("UNIDAD", Text)
    cliente = Column("CLIENTE", Text)
    telefono = Column("TELÉFONO", Text)
    fecha_pago = Column("FECHA DE PAGO", Text)
    dias_vencidos = Column("DÍAS DE VENCIDOS", Numeric(20, 4))
    concepto = Column("CONCEPTO", Text)
    monto_a_pagar = Column("MONTO A PAGAR", Numeric(20, 4))
    estatus_pipeline = Column("ESTATUS DE PIPELINE", Text)
    monto_pagado = Column("MONTO PAGADO", Numeric(20, 4))
    penalizacion_generada = Column("PENALIZACIÓN GENERADA", Numeric(20, 4))
    penalizacion_pagada = Column("PENALIZACIÓN PAGADA", Numeric(20, 4))
    saldo_sin_pen = Column("SALDO PENDIENTE SIN PENALIZACIÓN", Numeric(20, 4))
    saldo_con_pen = Column("SALDO PENDIENTE CON PENALIZACIÓN", Numeric(20, 4))
    parcialidades_vencidas = Column("NÚMERO DE PARCIALIDADES VENCIDAS TOTALES", Numeric(20, 4))
    total_vencido_sin_pen = Column("MONTO TOTAL VENCIDO SIN PENALIZACIÓN", Float)
    total_vencido_con_pen = Column("MONTO TOTAL VENCIDO CON PENALIZACIÓN", Float)
    moneda = Column("MONEDA", Text)
    
class AntigSaldos(Base):
    __tablename__ = "antig_saldos"
    folio = Column("FOLIO", String(255), primary_key=True)
    cliente = Column("CLIENTE", Text)
    proyecto = Column("PROYECTO", Text)
    fase = Column("FASE", Text)
    etapa = Column("ETAPA", Text)
    unidad = Column("UNIDAD", Text)
    correo = Column("CORREO ELECTRÓNICO", Text)
    telefono = Column("TELÉFONO", Text)
    fecha_pago = Column("FECHA DE PAGO", Text)
    saldo_vigente = Column("SALDO VIGENTE", Numeric(20, 4))
    dias_1_30 = Column("01 A 30 DÍAS", Numeric(20, 4))
    dias_31_60 = Column("31 A 60 DÍAS", Numeric(20, 4))
    dias_61_90 = Column("61 A 90 DÍAS", Numeric(20, 4))
    dias_91_120 = Column("91 A 120 DÍAS", Numeric(20, 4))
    mas_120_dias = Column("MÁS DE 120 DÍAS", Numeric(20, 4))
    mensualidades_vencidas = Column("MENSUALIDADES VENCIDAS", BigInteger)
    total_vencido = Column("TOTAL VENCIDO", Numeric(20, 4))
    cartera_total = Column("CARTERA TOTAL", Numeric(20, 4))
    total_pagado = Column("TOTAL PAGADO", Numeric(20, 4))
    porcentaje_vencido = Column("% VENCIDO", Numeric(20, 4))
    
        
class Amortizacion(Base):
    __tablename__ = "amortizaciones"
    
    folder_id = Column("folder_id", String(255), primary_key=True)
    number = Column("number", String(255), primary_key=True)
    concept = Column("concept", Text)
    date = Column("date", Text) 
    capital = Column(Numeric(precision=20, scale=4))
    interest = Column(Numeric(precision=20, scale=4))
    down_payment = Column(Numeric(precision=20, scale=4))
    total = Column(Numeric(precision=20, scale=4))
    penalized_amount = Column(Numeric(precision=20, scale=4))
    

class Cliente(Base):
    __tablename__ = "clientes"
    client_id = Column("client_id", String(255), primary_key=True)
    created_at = Column("created_at", Text)
    client_name = Column("client_name", Text)
    email = Column("email", Text)
    client_person = Column("client_person", Text)
    main_phone = Column("main_phone", Text)
    optional_phone = Column("optional_phone", Text)
    lead_source = Column("lead_source", Text)
    rfc = Column("rfc", Text)
    state = Column("state", Text)
    country = Column("country", Text)
    city = Column("city", Text)
    street = Column("street", Text)
    house_number = Column("house_number", Text)
    interior_number = Column("interior_number", Text)
    colony = Column("colony", Text)
    postal_code = Column("postal_code", Text)
    location = Column("location", Text)
    identification_type = Column("identification_type", Text)
    identification_number = Column("identification_number", Text)
    validity_identification = Column("validity_identification", Text)
    use_cfdi = Column("use_cfdi", Text)
    fiscal_regime = Column("fiscal_regime", Float)
    additional_emails_billing = Column("additional_emails_billing", Text) 
    pc_curp = Column("pc_curp", Text)
    pc_birthdate = Column("pc_birthdate", Text)
    pc_place_birth = Column("pc_place_birth", Text)
    pc_nationality = Column("pc_nationality", Text)
    pc_civil_status = Column("pc_civil_status", Text)
    pc_regime = Column("pc_regime", Text)
    pc_occupation = Column("pc_occupation", Text)
    pc_identification_type_id = Column("pc_identification_type_id", Float)
    mc_legal_name = Column("mc_legal_name", Text)
    mc_legal_rfc = Column("mc_legal_rfc", Text)
    mc_constitution_date = Column("mc_constitution_date", Text)
    mc_activity = Column("mc_activity", Text)
    mc_notary_name = Column("mc_notary_name", Text)
    mc_notary_public_name = Column("mc_notary_public_name", Text)
    mc_notary_public_number = Column("mc_notary_public_number", Text)
    mc_notary_public_catalog_republic = Column("mc_notary_public_catalog_republic", Float)
    mc_commercial_electronic_folio_number = Column("mc_commercial_electronic_folio_number", Text)
    mc_public_registry_state = Column("mc_public_registry_state", Text)
    mc_public_registry_date = Column("mc_public_registry_date", Text)
    mc_company_identification_type = Column("mc_company_identification_type", Float)
    mc_company_identification_number = Column("mc_company_identification_number", Text)
    mc_company_validity_identification = Column("mc_company_validity_identification", Text)
    mc_legal_representative_act_number = Column("mc_legal_representative_act_number", Float)
    mc_legal_representative_act_date = Column("mc_legal_representative_act_date", Text)
    mc_legal_representative_act_type = Column("mc_legal_representative_act_type", Text)
    mc_legal_representative_public_notary = Column("mc_legal_representative_public_notary", Text)
    mc_legal_representative_notary_number = Column("mc_legal_representative_notary_number", Float)
    mc_legal_representative_electronic_folio = Column("mc_legal_representative_electronic_folio", Float)
  
    


class GestionClientes(Base):
    __tablename__ = "notificaciones_gestion_clientes"
    
    id = Column(BigInteger, primary_key=True, autoincrement=True)
    folio = Column(String(255), index=True)
    client_id = Column(String(255), index=True)

    client_name = Column(Text)
    email = Column(Text)
    telefono = Column(Text)
    proyecto = Column(Text)
    etapa_cluster = Column(Text)
    m2 = Column(Numeric(20, 4))
    es_propietario_principal = Column(Boolean, default=False)
    permite_email_lote = Column(Boolean, default=True)      # Específico este lote
    permite_whatsapp_lote = Column(Boolean, default=True)   # Específico este lote
    permite_marketing_email = Column(Boolean, default=1)
    permite_marketing_whatsapp = Column(Boolean, default=1)
    

class ConfigEtapa(Base):
    __tablename__ = "config_etapas"
    
    id = Column(Integer, primary_key=True, index=True)
    proyecto = Column(String(255))
    etapa = Column(String(255), unique=True, nullable=False)
    total_folios = Column(Integer, default=0)
    etapa_activo = Column(String(255))   
    proyecto_activo = Column(String(255))